PKG_NAME="gst-python"
PKG_VERSION="1.19.2"
PKG_SHA256="7d41f171b5af8fd06f58bcf1dc9b46fbd9eee9367ededa635a412e55264456e9"
PKG_LICENSE="LGPL-2.1-or-later"
PKG_SITE="https://gitlab.freedesktop.org/gstreamer/gst-python"
PKG_URL="https://gitlab.freedesktop.org/gstreamer/gst-python/-/archive/${PKG_VERSION}/gst-python-${PKG_VERSION}.tar.gz"
PKG_DEPENDS_TARGET="toolchain pygobject gstreamer gst-plugins-base"
PKG_LONGDESC="GStreamer Python binding overrides"

PKG_MESON_OPTS_TARGET="-Dlibpython-dir=/usr/lib"
