name: Build Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y xfonts-utils libparse-yapp-perl gperf xsltproc patchutils lzop libxml-parser-perl libgirepository1.0-dev
      
    - name: Run build
      run: AUTOREMOVE=yes PROJECT=Generic ARCH=x86_64 make image
      
    - name: Archive image
      uses: actions/upload-artifact@v3
      with:
          name: images
          path: target/*.img.gz
          path: target/*.ova

